# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de6555613e3bf370e58714a8f66d069b872a7c6a520933eab9114e45abf3768f93771e081066e6a7c1e3746a965347b40b7c576ebf76ae37b43b8fbabdd0b159

test:
  secret_key_base: d104ad053a6014352257c8a7ebc4615ac2779d7dc5802637e885d5b2bfd19edc39d382d7ce13239c05f3355936591b8724fee86d0b1272a46e5c764ee85a202c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
